# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]


jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m ensurepip --upgrade
          python -m pip install Flask PyInstaller
      - name: Build with PyInstaller
        run: |
          echo "[]" > babsmile.json
          pyinstaller babsmilemanager.py -F \
          --add-data babsmilemanager/static/:babsmilemanager/static/ \
          --add-data babsmilemanager/templates/:babsmilemanager/templates/ \
          --add-data babsmile.json:babsmile.json  \
          --console --hide-console minimize-late \
          --icon babsmilemanager/static/favicon.ico
          chmod +x dist/babsmilemanager
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: BabSmileManager-linux-amd64
          path: dist/*
  build-windows:
    strategy:
      fail-fast: false
    runs-on: 'ubuntu-latest'
    container: docker.io/alberic89/wine-devel-python:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with PyInstaller
        if: ${{ matrix.os == 'windows-amd64' }}
        run: |
          echo "[]" > babsmile.json
          wine pyinstaller babsmilemanager.py -F \
          --add-data babsmilemanager/static/:babsmilemanager/static/ \
          --add-data babsmilemanager/templates/:babsmilemanager/templates/ \
          --add-data babsmile.json:babsmile.json  \
          --console --hide-console minimize-late \
          --icon babsmilemanager/static/favicon.ico
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: BabSmileManager-windows-amd64
          path: dist/*
